# Generated by Django 4.1.5 on 2023-02-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
    ]
